### ISSUE TITLE
Future request

### ISSUE THREAD

**Issue by Tinuz97** [Mr-Kodi/repository.fenomscrapers#1]
No need to hurry, but if you can make strings.po support for Fenom Scrapers,i can translate them to Dutch also. (just a idea).
Greetings Tinuz.

**Comment by Mr-Kodi** [comment]
sure.  I saw you did the translation for **My Accounts** so we can do the same here.  I'm actually tweaking an update right now I was planning to push out tonight so sooner the better

**Comment by Tikipeter** [comment]
Hi Tinuz. :)
The latest version (v.1.0.4) has language string support.
Here is the ENG `strings.po` if you need it in order to translate:
[eng strings.zip](https://github.com/Mr-Kodi/repository.fenomscrapers/files/5308119/eng.strings.zip)

I've separated the provider strings from #32061 - #32100 for hosters and #32101-32140 for torrents. I don't think you need to translate them at all, but you know best.

Good Luck and as always many, many thanks. :)

**Comment by Tinuz97** [comment]
@Mr-Kodi 
is this one double? Or a typo? 2 times username,i think one of them is password?

msgctxt "#32028"
msgid "Easynews Username"
msgstr "Easynews Gebruikersnaam"

msgctxt "#32029"
msgid "Easynews Username"
msgstr ""

**Comment by Tinuz97** [comment]
i do the hosters en torrents also, because of this (as a example)

msgctxt "#32104"
msgid "BTSCENE (Pack capable)"
msgstr "BTSCENE (Pack geschikt)"

**Comment by Tinuz97** [comment]
> @Mr-Kodi @Tikipeter
> is this one double? Or a typo? 2 times username,i think one of them is password?
> 
> msgctxt "#32028"
> msgid "Easynews Username"
> msgstr "Easynews Gebruikersnaam"
> 
> msgctxt "#32029"
> msgid "Easynews Username"
> msgstr ""

So if this is a typo,and it needs to be Password,you can edit it like this,i leave the file how it is,so correct is afterwards if needed.
Almost done,uploading asap (doing a check at the moment)

msgctxt "#32029"
msgid "Easynews Password"
msgstr "Easynews Wachtwoord"

**Comment by Tinuz97** [comment]
Dutch strings (please also read one message above this one)
[resource.language.nl_nl.zip](https://github.com/Mr-Kodi/repository.fenomscrapers/files/5312017/resource.language.nl_nl.zip)

**Comment by Tinuz97** [comment]
Most,but not all are working,weird (i translated all), any idea?
![image](https://user-images.githubusercontent.com/47715606/94811388-97961b80-03f5-11eb-9813-1112ed1e8ca4.png)

**Comment by Tinuz97** [comment]
I think i see where it goes wrong?
i have the idea that this does not belong in the string.po, looks like Fen addon strings.
So please check the Dutch language file before adding it (all translations are correct, but also see my comment above)

![image](https://user-images.githubusercontent.com/47715606/94812084-8994ca80-03f6-11eb-9d0c-2fe76959e7ae.png)

**Comment by Tikipeter** [comment]
Thanks Tinuz!
You're right on both counts, I mistakenly left those id's at the end. So sorry you translated them. And Easynews Password is correct too.
These can go out next update. 👍 🥇 💯 
Great Job mate!!

**Comment by Tinuz97** [comment]
I think you forgot to edit the id's I guess. 
Because in the release version it shows the same (translations for Fen addon) @Mr-Kodi 

![Screenshot_20201004-014010](https://user-images.githubusercontent.com/47715606/95003755-b0175900-05e2-11eb-9d49-acea1afa57ed.jpg)

**Comment by Tinuz97** [comment]
It also has no torrents listed because of that I guess (like the section hosters, where you can enable or disable a torrent scraper)
Please check it 😊😀

**Comment by Tikipeter** [comment]
I fixed the Dutch `strings.po` and forgot to fix the bloody English one. That "My Accounts" issue and real life work currently has ground me into the dirt. My brain's gone to jelly.

You might have to switch to English to change those settings Tinuz, until a new release is ready (you can use the external Scrapers Manager in Fen Tools if you want as well to tur these on/off).

**Comment by Tinuz97** [comment]
Thanks, working great now 🎉👍

![Screenshot_20201006-000647](https://user-images.githubusercontent.com/47715606/95137248-f813b880-0767-11eb-8743-83414a8eafb0.jpg)

**Comment by Tinuz97** [comment]
I did see that Easynews still has gebruiksnaam/gebruikersnaam (in Dutch, did not check English, maybey it has username/username also.) 

First one is correct : Gebruikersnaam (username in English). 
2nd one must be Wachtwoord (Password in English). 

Further no issues found, just a minor translation thingy. 
![Screenshot_20201014-123329](https://user-images.githubusercontent.com/47715606/95977795-94e5ee00-0e19-11eb-9ddf-b797676e533f.jpg)

**Comment by Tinuz97** [comment]
@Tikipeter or @Mr-Kodi or @123Venom  (no idea who i need to tag,lol)

Updated strings.po ,compatible with the latest FenomScrapers 1.1.0 (translated and added the extra lines)

[Dutch.zip](https://github.com/Mr-Kodi/repository.fenomscrapers/files/5464681/Dutch.zip)

**Comment by Tinuz97** [comment]
Also noticed that something in settings.xml is (i think) not correct (look at 2 times easynews,ororo gone)

![image](https://user-images.githubusercontent.com/47715606/97699909-38d2c900-1aab-11eb-860f-b58b0aa790ac.png)

**Comment by Tinuz97** [comment]
I think i noticed something double in the settings.xml while checking the language codes?

**Comment by Tinuz97** [comment]
I think i noticed something double in the settings.xml ,while checking the label numbers for the strings.po?

![image](https://user-images.githubusercontent.com/47715606/97702038-a03e4800-1aae-11eb-93f5-bf91d974fd6e.png)

**Comment by 123Venom** [comment]
ha...looks like the joys of copy/paste and forgetting an edit...lol.  I'll fix that and include your latest dutch.zip while in there.

**Comment by 123Venom** [comment]
ok we got to be careful here.  Your dutch translation are for My Accounts but you posted it here in FenomScrapers and had I not looked I would have over-written it.  While I'm fixing that settings.xml gaff did you happen to have any dutch translation changes for FenomScrapers? Or is that one good?

**Comment by Tinuz97** [comment]
Dang, my bad. Because I was busy with both.
I will check Fenomscrapers in a minute (did some extra translations there also.)

**Comment by 123Venom** [comment]
ok I'll take those FenomScraper Dutch translation changes if ya got em and include it with the settings.xml changes and push an update.  Appreciate it!

**Comment by 123Venom** [comment]
I think what I'd like to do with any future additions of added lang strings I'd like to send it over to you to touch up, if that's ok?  That way we do one push and avoid a 2nd push the next day for Dutch translations.

**Comment by Tinuz97** [comment]
I'll check Fenomscrapers later,after the fix i guess (settings.xml), because i can't check the correct numbers for the translations. 
So My accounts is good for now. (that one is correct)

**Comment by 123Venom** [comment]
We worked together on this one so during our shuffle if he's use to already doing that it just got overlooked.

**Comment by 123Venom** [comment]
> 
> 
> I'll check Fenomscrapers later,after the fix i guess (settings.xml), because i can't check the correct numbers for the translations.
> So My accounts is good for now. (that one is correct)

I'd rather wait for it than push 2 updates.  I'll hold off on FenomScraper's settings.xml fix till then.  I onlly just took out that duplicate entry you noted...all else is the same.

**Comment by Tinuz97** [comment]
@123Venom 

Just tag me next time if you need new translations, I am pretty fast with translations and fast in reactions. (@Tikipeter does tag me also for Fen if he needs new translations, fast responding over here) 

Did see a new update, but not all are correct translations. 

Here are some fixes:

msgctxt "#32041"
msgid "Clean Settings file"
msgstr "Reinig Instellingenbestand "


msgctxt "#32042"
msgid "{} Obsolete Settings Entries Removed"
msgstr "{} Verouderde Instellingen Gegevens Verwijderd"

msgctxt "#32040"
msgid "[COLOR FFA0C12C]-- Torrent scraper Info --[/COLOR]"
msgstr "[COLOR FFA0C12C]-- Torrent scraper Info --[/COLOR]"

msgctxt "#32043"
msgid "Error Cleaning Settings.xml. Old settings.xml files Restored."
msgstr "Fout Bij Het Opschonen Van Settings.xml. Oude settings.xml bestanden Hersteld"

**Comment by 123Venom** [comment]
I'll swap those out in next update.  Sorry I used google translate for the few strings I added and guess something was off with it.

**Comment by 123Venom** [comment]
@Tinuz97

Need your dutch translation for a new setting we're adding to MA for debrid account expiry notification. 
"Account Expiry Notification"
I'd use google translate but that didn't work so well last time..lol

**Comment by Tinuz97** [comment]
Account Verlopen Notificatie

**Comment by 123Venom** [comment]
@Tinuz97 

While doing a scraper update I decided to group the "Premium Hosters" a little better.  We have account required scrapers mixed in with even a "local" library scraper.  So my thought is to make two new headings and need your Dutch translation for them. The two new headings are....

"**Account Required Scrapers**"
"**Local Scrapers**"

**Comment by Tinuz97** [comment]
@123Venom

"Account Vereiste Scrapers"

"Lokale Scrapers"

**Comment by Tinuz97** [comment]
Offtopic, but i noticed also a cloudscraper update, Release 1.2.50 (by VeNoMouS). Hopefully that would fix rlsbb links, or is it just me that rlsbb does now show any results for a long time?

**Comment by 123Venom** [comment]
Rlsbb is v2 challenge now when tested 3 days ago..dead and gone so I removed in release I'm about to push.  It's even dead in Seren, tested to be sure. There's no free solve of v2.  I Read Venomous's update briefly and I know he's never going to release his v2 solve for free so from what I read that update just adds some new paid solves...useless for us.  

Rapidmoviez has been resurrected though as it was lost about 6 months back to v2 solve but for some reason they've reverted...happens and we need to just check it from time to time so I'm not sure when that sucker actually came back.

Give up on hosters bro!  They're rubbish..lol.  I maintain them but on a very smaller scale compared to a year ago because they're just to time consuming and a royal thorn to me.  I've actually yanked 5 junk hosters and 4 lost to v2 challenge in update I'm pushing.  I predict 6 month from now I won't touch a hoster anymore.

**Comment by Tinuz97** [comment]
Thx for the info 🙂

**Comment by 123Venom** [comment]
@Tinuz97 need your translation for a new bool/setting I'm adding to EasyNews scraper

"Title Check Results"

**Comment by Tinuz97** [comment]
@123Venom

Titelcontrole Resultaten

**Comment by Tinuz97** [comment]
@123Venom  i am missing (i think) this one in the strings.po (compared english strings with the dutch strings file) ,maybey not used,no idea, a check-up, maybey you see any more translatations that need to be added?

msgctxt "#32140"
msgid "Clear ALL Extra Undesirables"
msgstr ""

Dutch one:

msgctxt "#32140"
msgid "Clear ALL Extra Undesirables"
msgstr "Wis ALLE Extra Ongewenste "

**Comment by Tinuz97** [comment]
@123Venom  Also found these:

msgctxt "#32084"
msgid "No User Undesirables Set"
msgstr ""

msgctxt "#32085"
msgid "Select to Enable/Disable"
msgstr ""

msgctxt "#32086"
msgid "Select to Remove From List"
msgstr ""

msgctxt "#32087"
msgid "Success"
msgstr ""

Dutch:

msgctxt "#32085"
msgid "Select to Enable/Disable"
msgstr "Selecteer om In/Uit te Schakelen"

msgctxt "#32086"
msgid "Select to Remove From List"
msgstr "Selecteer om uit Lijst te Verwijderen"

msgctxt "#32087"
msgid "Success"
msgstr "Succes"

**Comment by 123Venom** [comment]
I'll dial these changes in for next update.  Thank you.
