### ISSUE TITLE
Venom repo updates

### ISSUE THREAD

**Issue by marson53** [Mr-Kodi/repository.fenomscrapers#12]
I'm using Kodi ver 18.9 , and I've just got an update for 6 items ,that point to Venom repo ver 12.0.2 but they won't update, I get the error, the dependency python ver 3  could not be satisfied on all 6  CherryPy ,Metadata and artwork, Musicbrainz , Skin Helper, Skin Helper Widgets, The TVDB API v2 , I assume these updates are for Kodi 19, but are showing to update in Kodi 18.9 , I just wanted to let you know, Thanks for all your hard work

**Comment by 123Venom** [comment]
Honestly they mucked with Marcel's beta repo so bad it broken the Venom repo and I was forced to removed it and Auramod from the Venom repo.  The best way to deal with it is force install from zip...then use the file manager source location for the Venom repo and install v1.18.  idk what v12.02 is referencing as that's not a version of mine.
