### ISSUE TITLE
[BUG] Nyaa.si search issue

### ISSUE THREAD

**Issue by rehannali** [Mr-Kodi/repository.fenomscrapers#14]
Hi, as `nyaa.si` is available in search engine and it is good quite sometimes but i have problem with search some of the titles as it is available in `nyaa.si` website but when i tried to use it with `kodi` and search it, it didn't show me `nyaa.si` results.

The example would be `seven deadly sins` anime. 
Maybe it will get refine and search every title does anime have. Any help or solution to this problem would be appreciated.

**Comment by rehannali** [comment]
@123Venom Could you suggest dedicated anime addon for Kodi if possible?

**Comment by 123Venom** [comment]
I'm not into Anime myself but one I often see mentioned is Kaito

**Comment by rehannali** [comment]
@123Venom Thanks for suggestion and it works well exactly it needed to be worked.
