### ISSUE TITLE
Defined extra undesirables not filtering properly

### ISSUE THREAD

**Issue by jaimsitecom** [Mr-Kodi/repository.fenomscrapers#15]
First of all thanks for this terrific addon. Super nice once paired with my debrid accounts. It’s so awesome. 

Now, I tried to use the ‘Define Extra Undesireables’ inside the Torrent settings tab, by adding ‘1080p.Ultradox’. But these russian Betwin nuisance video packs still get whitelisted and allowed. Is there something i should add onto the custom settings list to finally block ULTRADOX?

thanks again and more pwer to you!

**Comment by 123Venom** [comment]
Try using simply `ultradox`, lower case.  We compare against the magnets `release_title` info portion and it's in lower case.  We need to address that case sensitive issue.  Test that and let me know

**Comment by jaimsitecom** [comment]
Yes! That worked! Wow thanks so much!!!

**Comment by jaimsitecom** [comment]
> Try using simply `ultradox`, lower case. We compare against the magnets `release_title` info portion and it's in lower case. We need to address that case sensitive issue. Test that and let me know

Sir i know this isnt the forum for issues for Venom addon. But i wanna know how to report issues/bugs?  Sorry again.
