### ISSUE TITLE
Venom kodi library puts unaired tv episodes a day in advance

### ISSUE THREAD

**Issue by jaimsitecom** [Mr-Kodi/repository.fenomscrapers#16]
Since Venom version 5.0.1 , it started downloading .strm tv episodes a day in advance. I tried it up to the latest 5.0.6 version and it still does download .strm tv episodes a day ahead. So i had to go back to version 5.0.0 so that it would only download tv episodes into the kodi library at the correct day (air date). 

Is this intentional now starting from version 5.0.1?  Coz if so, I don’t mind sticking to version 5.0.0 so that my tv schedules are in correct dates/order. 

Also, I had the ‘show unaired seasons/episodes’, unchecked. Also clicked the Library setting ‘24H delay before import’ just to check if it would help but it still inserts tv episodes a day earlier than real airtime. 

Again thanks for the awesome addons, Venom!

**Comment by Tikipeter** [comment]
Not related to FenomScrapers in any way, shape or form.
