### ISSUE TITLE
Ibit Torrent

### ISSUE THREAD

**Issue by marson53** [Mr-Kodi/repository.fenomscrapers#18]
Would It Be Possible to Add https://ibit.to Torrent, To Fenomscrapers , Thanks

**Comment by 123Venom** [comment]
That ones been on my radar for like a year...lol.  It's a 2 request site to fetch the magnet and the server response time last I tested was slow.  At this time I think we have more torrents than we even need.  I only use 6-7 myself and enabling more is just wasting scrape time and more often than not your just scraping duplicates.  Here's a list of other sites that's been in my **Potential new torrent scrapers** folder for some time.

[https://bitcq.com](https://bitcq.com)
[https://ibit.to](https://ibit.to)
[https://01torrent.unblockit.li/](https://01torrent.unblockit.li/)
[https://otorrents.com/](https://otorrents.com/)

Those are not even anything to excite me enough to include them. 30+ scrapers is MORE than enough.
