### ISSUE TITLE
Extratorrent

### ISSUE THREAD

**Issue by marson53** [Mr-Kodi/repository.fenomscrapers#20]
Extratorrent seems to be back working hxxps://extratorrent.si/

**Comment by 123Venom** [comment]
my luck...I usually give a source 2 weeks and if still down I remove it.  That one has been down longer than that and the very next day after I yanked it it is indeed back up again.  I'll add it back..not one I use myself..thanks for checking. **magnet4you** was also removed with that last update and it's still down.
