### ISSUE TITLE
4400 (new) TV Show not being scraped

### ISSUE THREAD

**Issue by Nuklear92** [Mr-Kodi/repository.fenomscrapers#22]
Okay, that new crappy reboot show "4400" which there was an original one called "The 4400". This new one in particular is **not** being scrapped correctly. I doubled checked, cleared scrapers cache, etc. It's only being scraped by **Hoster** sources not **Torrent** ones. I doubled checked other series with title names in numbers like, **24**, **The 100** even the original "The 4400" and they all seems to scrape eps correctly. 

Honestly, I'm not interested in the show myself but perhaps this could be an issue to other users that might be interested in watching this show and doesn't have any **Hoster** sources enabled by default.

Just to confirm, I decided to open this issue here in Fenomscrapers as I doubled checked both **FEN** and **VENOM** Addons and they both are presenting the same issue, so I guessed it might had to do with Fenomscrapers. 🤔

**Comment by 123Venom** [comment]
Confirmed.  Will be fixed in next release.  Thank you.
