### ISSUE TITLE
“And Just like That” Scraping Issue (Internal + External)

### ISSUE THREAD

**Issue by tundrablasen** [Mr-Kodi/repository.fenomscrapers#27]
So it seems there is a scraping issue with the new HBO Max Show  “And Just like That…”

http://www.themoviedb.org/tv/116450-and-just-like-that

It’s the new sex and the city spin off and obviously often female viewers want to see that show.

anyway FENOMSCRAPERS does not find any torrent sources for this show. Not externally not internally. Even though many many torrents are cached in Premiumize and also I have added manually torrents from rarbg to my PM Cloud. Both doesn’t get detected.

it is NOT related with the undesirables issue from previous fenomscrapers versions. (At least I think that). Because I have 2.0.7 and everything else up to date and other shows/movies scrape just fine.

i checked other kodi addons which does not utilise fenomscrapers and they detect cached sources for this show just fine. 

Initial,y I thought it has something to do with the “…” in the show name which no source has in their file name.

**Comment by 123Venom** [comment]
I had no problem pulling up plenty of cached torrents on S01E01 of that show.

<img width="1017" alt="and just like that" src="https://user-images.githubusercontent.com/46383815/145706473-1c2a2395-fbea-423e-ab59-0732897586c6.PNG">

Also cloud sources are covered by and addon NOT FenomScrapers.

**Comment by tundrablasen** [comment]
Thank you for reply. Interesting. I tried FEN and as Alternative Seren. Seren worked fine. 

so it seems to be a FEN related issue. Opened an issue over at tikipeter repo.

**Comment by 123Venom** [comment]
I'm sure once tikipeter is available he'll fix it as he's always quick.
