### ISSUE TITLE
Movie title with “ / “ not being scraped

### ISSUE THREAD

**Issue by Nuklear92** [Mr-Kodi/repository.fenomscrapers#28]
A recent 2021 released movie called **Mother/Android** is not being scrapped by default unless you open **context menu** on either **FEN or Venom** and select the scrape with **Custom Value/Query** and either take out the **"/"** in the middle of the title or replace it by a **"."** dot which is the way it's being uploaded **"Mother.Android.2021"**. I found it odd because before I went ahead and create this report I also double checked with Seren, which is tied with A4kscrapers to verify if it has the same issue and to my surprise It's scraping the title correctly by default. 

I was going to ask, are these perhaps missing strings that maybe A4kscrapers is doing when it's performing a scrape that Fenomscrapers is missing. And does this apply to other similar titles out there that perhaps are facing a similar issue when you guys end up pushing a hotfix for this title in particular. Or this will only apply for this single title? 🤔

**Comment by 123Venom** [comment]
I'm NOT the a4kscraper dev and to think I'm going to hunt thru HIS code for YOUR answer I have to ask...why would I?  If your point is to say "well they do it right and you do not" then I'm inclined to tell you then go use it and I have nothing further to do here...get it?  so do not do it from here on out because it's offensive and not a case I partake in.

So moving forward with more meaningful material.  It seems our FenomScrapers query returns results but our title check is where that fails on the `/` character.  It's a very unusual case for sure but preliminary tests removing the `/` from our title check is solving the issue.  I'll fix this in next uipdate

**Comment by Nuklear92** [comment]
> I'm NOT the a4kscraper dev and to think I'm going to hunt thru HIS code for YOUR answer I have to ask...why would I?  If your point is to say "well they do it right and you do not" then I'm inclined to tell you then go use it and I have nothing further to do here...get it?  so do not do it from here on out because it's offensive and not a case I partake in.
> 
> 
> 
> So moving forward with more meaningful material.  It seems our FenomScrapers query returns results but our title check is where that fails on the `/` character.  It's a very unusual case for sure but preliminary tests removing the `/` from our title check is solving the issue.  I'll fix this in next uipdate

Thanks for making the fix possible for the next update.

My apologies for mentioning A4kscrapers as an example, I didn't thought you were going to get so triggered by it. Everything I explained was mainly as a comparison and surprised that it did scraped the same movie without issue. Funny thing is I've also told the dev in past about a similar issue that his package was having compared to Fenomscrapers that was working fine and he never once responded back with the same attitude or thought I was asking him to go and dig into Fenomscrapers's code to look for a fix. He simply replied with your second paragraph format as he automatically understood I was doing a simple comparison to verify it was indeed something wrong with the title being scraped using his scraper. 

Either way, my apologies again now I understand what I should do before reporting another issue in the near future.
