### ISSUE TITLE
TVOS settings.xml clearing error

### ISSUE THREAD

**Issue by copperlab** [Mr-Kodi/repository.fenomscrapers#29]
Seeing a problem where settings.xml can't be cleared on TVos version.  This happens on a fresh install.  Can't seem to get past it.

**Comment by 123Venom** [comment]
Need a bit more details.  What do you mean "settings.xml can't be cleared"?  Are you talking about the settings cleaner that occurs on an update?  I'm also not following what you mean by "Can't seem to get past it."

**Comment by copperlab** [comment]
Ok.  I will try to elaborate.  Fresh install on 19.3 TVos.  Getting an error with venom and fen with 0 results.  Go through kodi to clean settings file and getting the error: FenomScrapers Module settings.xml could not be cleaned.  Reverting to old settings.xml file.  

Same install on ios works fine.  So not sure if it is a kodi problem on tvos.  Or a module problem on tvos.  But something is different.

Just haven't found any information on this problem via google.  And I can repeat it on two appletv products.  And I don't get the problem on two ios products.

Thanks

**Comment by 123Venom** [comment]
Unfortunately I do not possess the equipment to test that.  You'd have to pull the logs for me to have any hope of knowing what's going on. venom.log, kodi.log, and fenomscraper.log.

**Comment by Tikipeter** [comment]
>Go through kodi to clean settings file

What do you mean by this? I am unaware of that feature in Kodi.

Also if you could post a log of the errors from Venom and Fen when you attempt a scrape that would be great.
