### ISSUE TITLE
[Request] Add Nyaa (nyaa.si) (anime torrents) as a source 

### ISSUE THREAD

**Issue by mathu204** [Mr-Kodi/repository.fenomscrapers#4]
A4kscrapers from Seren has this scraper for reference

**Comment by mathu204** [comment]
Nyaa and Nyaa2 are also here (it’s for a different app tho but not sure if it can help or not so just putting it here) (also not sure the diff between Nyaa and nyaa2) if u could atleast get Nyaa it would be great 

https://raw.githubusercontent.com/itzAki07/scraper/main/scraper.json

**Comment by 123Venom** [comment]
We have nyaa in there and it uses https://nyaa.si .  I tested 3 titles and seems to work fine.  Granted I wrote that thing about a year ago and I'll be honest...title matching Anime is major pita.
