### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MrC001** [Mr-Kodi/repository.fenomscrapers#6]
Is it possible now or be added the ability to set order of scrappers??

**Comment by Tikipeter** [comment]
You would have to request this through the addon you use, and even then I doubt it would be adopted.
With addons returning mainly cached/uncached torrent links through debrid providers, there is no reason to set the order of the scrapers. Or is there?

The order of the debrid providers is a different story, of course. That can have benefits.

**Comment by MrC001** [comment]
The only one that would make a diff is orion.

**Comment by 123Venom** [comment]
The scrapers themselves have a hard coded priority value based on speed tests I've done so fastest scrapers will run first.  There's really no further benefit to changing our current system.
